"""Initial_migration_clean

Revision ID: 3ec4f631406e
Revises: 
Create Date: 2025-12-15 22:10:29.653201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec4f631406e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_activity_types_id'), 'activity_types', ['id'], unique=False)
    op.create_table('historical_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dapil', sa.String(), nullable=True),
    sa.Column('kabupaten', sa.String(), nullable=True),
    sa.Column('kecamatan', sa.String(), nullable=True),
    sa.Column('desa', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('total_votes', sa.Integer(), nullable=True),
    sa.Column('election_year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_votes_dapil'), 'historical_votes', ['dapil'], unique=False)
    op.create_index(op.f('ix_historical_votes_desa'), 'historical_votes', ['desa'], unique=False)
    op.create_index(op.f('ix_historical_votes_election_year'), 'historical_votes', ['election_year'], unique=False)
    op.create_index(op.f('ix_historical_votes_id'), 'historical_votes', ['id'], unique=False)
    op.create_index(op.f('ix_historical_votes_kabupaten'), 'historical_votes', ['kabupaten'], unique=False)
    op.create_index(op.f('ix_historical_votes_kecamatan'), 'historical_votes', ['kecamatan'], unique=False)
    op.create_index(op.f('ix_historical_votes_source'), 'historical_votes', ['source'], unique=False)
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_logs_id'), 'import_logs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nik', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nik'), 'users', ['nik'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=True),
    sa.Column('dapil', sa.String(), nullable=False),
    sa.Column('location_hierarchy', sa.JSON(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('target_participants', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('nik', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('kecamatan', sa.String(), nullable=True),
    sa.Column('desa', sa.String(), nullable=True),
    sa.Column('kampung', sa.String(), nullable=True),
    sa.Column('rt_rw', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nik', name='unique_attendee_nik')
    )
    op.create_index(op.f('ix_attendees_id'), 'attendees', ['id'], unique=False)
    op.create_index(op.f('ix_attendees_nik'), 'attendees', ['nik'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendees_nik'), table_name='attendees')
    op.drop_index(op.f('ix_attendees_id'), table_name='attendees')
    op.drop_table('attendees')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_nik'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_import_logs_id'), table_name='import_logs')
    op.drop_table('import_logs')
    op.drop_index(op.f('ix_historical_votes_source'), table_name='historical_votes')
    op.drop_index(op.f('ix_historical_votes_kecamatan'), table_name='historical_votes')
    op.drop_index(op.f('ix_historical_votes_kabupaten'), table_name='historical_votes')
    op.drop_index(op.f('ix_historical_votes_id'), table_name='historical_votes')
    op.drop_index(op.f('ix_historical_votes_election_year'), table_name='historical_votes')
    op.drop_index(op.f('ix_historical_votes_desa'), table_name='historical_votes')
    op.drop_index(op.f('ix_historical_votes_dapil'), table_name='historical_votes')
    op.drop_table('historical_votes')
    op.drop_index(op.f('ix_activity_types_id'), table_name='activity_types')
    op.drop_table('activity_types')
    # ### end Alembic commands ###
