"""add_refresh_token_table

Revision ID: 52fbb29cee5d
Revises: 6a1b2c3d4e5f
Create Date: 2025-12-25 14:41:26.849559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52fbb29cee5d'
down_revision: Union[str, Sequence[str], None] = '6a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'kecamatan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'kecamatan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
